FROM node:latest as build-node
WORKDIR /app
COPY simparse.web/package*.json ./
RUN npm install
COPY ./simparse.web/ .
RUN npm run build

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY /Simparse.FrontEnd/*.csproj .
RUN dotnet restore
COPY /Simparse.FrontEnd/ .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out .
COPY --from=build-node /app ./wwwroot/

ENTRYPOINT ["dotnet", "Simparse.FrontEnd.dll"]